name: 'publish'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: windows-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read changelog
        run: |
          # Read changelog only
          echo "CHANGELOG_BODY<<EOF" >> $env:GITHUB_ENV
          $changelog = Get-Content CHANGELOG.txt -Raw
          echo "$changelog" >> $env:GITHUB_ENV
          echo 'EOF' >> $env:GITHUB_ENV

          # Read changelog + release notes
          echo "RELEASE_BODY<<EOF" >> $env:GITHUB_ENV
          echo "$changelog" >> $env:GITHUB_ENV
          echo ([Environment]::NewLine) >> $env:GITHUB_ENV
          $version = (Get-Content package.json | ConvertFrom-Json).version
          (Get-Content RELEASE.md -Raw) -replace '__VERSION__', "$version" >> $env:GITHUB_ENV
          echo 'EOF' >> $env:GITHUB_ENV
        shell: pwsh

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Build Tauri app
        id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tauriScript: pnpm tauri
          tagName: ${{ github.event_name == 'pull_request' && 'v__VERSION__-pre' || 'v__VERSION__' }}
          releaseName: ${{ github.event_name == 'pull_request' && 'OverBuddy v__VERSION__ (Preview)' || 'OverBuddy v__VERSION__' }}
          releaseBody: ${{ env.CHANGELOG_BODY }}
          releaseDraft: false
          prerelease: ${{ github.event_name == 'pull_request' }}

      - name: Update Release Body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BODY: ${{ env.RELEASE_BODY }}
          RELEASE_ID: ${{ steps.tauri.outputs.releaseId }}
          REPO: ${{ github.repository }}
        run: |
          $headers = @{
            Authorization = "Bearer $env:GITHUB_TOKEN"
            Accept        = "application/vnd.github+json"
            "X-GitHub-Api-Version" = "2022-11-28"
          }

          $body = @{
            body = "$env:RELEASE_BODY"
          } | ConvertTo-Json -Compress

          Invoke-RestMethod -Uri "https://api.github.com/repos/$env:REPO/releases/$env:RELEASE_ID" `
                            -Method Patch `
                            -Headers $headers `
                            -Body $body
        shell: pwsh
